# Generated by Django 5.2.6 on 2025-09-29 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_activity',
            field=models.DateTimeField(auto_now=True, verbose_name='Последняя активность'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'Клиент'), ('manager', 'Менеджер проекта'), ('event_planner', 'Организатор мероприятий'), ('admin', 'Администратор сайта')], default='client', max_length=20, verbose_name='Роль'),
        ),
    ]
